export enum Category {
  JAKOSC_BRAIKI_ODPADY,
  WYDAJNOSC_TECHNOLOGIA,
  KOMUNIKACJA_WSPOLPRACA,
  ZAPASY_TRANSPORT,
  PRODUKCJA_W_TOKU_LAYOUT,
  AWARIE_PRZESTOJE,
  PRZEZBROJENIE_SETUP,
  BHP_ERGONOMIA_SRODOWISKO
}

