export enum EsubmissionStatusEnum {
  NOWE_ZGLOSZENIE,
  EDYCJA,
  DO_SPRAWDZENIA_LIDER,
  ZATWIERDZONO_LIDER,
  DO_SPRAWDZENIA_KIEROWNIK,
  ZATWIERDZONO_KIEROWNIK,
  DO_SPRAWDZENIA_KOORDYNATOR,
  ZATWIERDZONO_KOORDYNATOR,
  WDROZONE,
  ROZWIAZANY,
  ARCHIWUM,
  DO_POPRAWY,
  ZMIANA_RECENZENTA
}
